brew "awscli"
brew "fzf"
brew "gh"
cask "1password"
cask "google-chrome"
cask "raycast"
cask "rectangle"
cask "visual-studio-code"
cask "warp"

## Work
brew "cloudflared"
cask "studio-3t"
cask "mongodb-compass"
cask "loom"

