[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[keyboard]
bindings = [
    { key = "F11", action = "ToggleMaximized" }
]