# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$hostname[$directory$git_branch]($style)\n$character"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold #A5D6A7)[❯](bold #FFF59D)[❯](bold #FFAB91)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '

[aws.region_aliases]
us-east-1 = 'us'
eu-central-1 = 'eu'

[nodejs]
format = 'via [🤖 $version](bold green) '

[hostname]
ssh_only = true
format = "[🖥  REMOTE](bold red) "
disabled = false